# Player Name Matching Between Datasets

This notebook reads two football player CSV datasets and matches player names between them.

## 1. Import Required Libraries
Import pandas and any other necessary libraries for data manipulation and matching.

In [ ]:
import pandas as pd
import numpy as np
import re
import unicodedata

## 2. Load CSV Files
Read the two CSV files into pandas DataFrames.

In [16]:
# Load the CSV files into DataFrames
players_2024_df = pd.read_csv('../datasets/Football Players Datasets 2015 - 2024/Latest Football  Players 2024 Data.csv')
transfermarkt_players_df = pd.read_csv('../datasets/Football Data from Transfermarkt/players.csv')

## 3. Preview DataFrames
Display the first few rows of each DataFrame to understand their structure, focusing on the 'Players' and 'name' columns.

In [17]:
# Preview the first few rows of each DataFrame
print("Players 2024 DataFrame:")
print("Number of players in 2024 dataset:", len(players_2024_df))
display(players_2024_df[['Players']].head())

print("Transfermarkt Players DataFrame:")
print("Number of players in Transfermarkt dataset:", len(transfermarkt_players_df))
display(transfermarkt_players_df[['name']].head())

Players 2024 DataFrame:
Number of players in 2024 dataset: 1216

        Players
0  Lionel Messi
1  Lionel Messi
2  Lionel Messi
3  Lionel Messi
4  Lionel Messi

Transfermarkt Players DataFrame:
Number of players in Transfermarkt dataset: 34312

                 name
0      Miroslav Klose
1  Roman Weidenfeller
2    Dimitar Berbatov
3               Lúcio
4          Tom Starke

## 4. Match Player Names Across DataFrames
Perform a merge operation to match player names from the 'Players' column in the first DataFrame with the 'name' column in the second DataFrame.

In [18]:
# Merge DataFrames on normalized player names
matched_df_plain = pd.merge(
    players_2024_df,
    transfermarkt_players_df,
    left_on='Players',
    right_on='name',
    how='inner',
    suffixes=('_2024', '_tm')
)
print(f"Number of matched players: {len(matched_df_plain)}")

Number of matched players: 1002

## 5. Display Matched Results
Show the resulting DataFrame with matched player names and relevant columns from both datasets.

In [19]:
# Display the matched results
# Show selected columns for clarity
columns_to_show = [
    'Players', 'Teams', 'Seasons', 'Matches', 'Goals', 'Assists', 'Seasons Ratings',
    'name', 'player_id'
]
display(matched_df_plain[columns_to_show].head(20))

,Players,Teams,Seasons,Matches,Goals,Assists,Seasons Ratings,name,player_id
0,Lionel Messi,InterMiami,2024,15,14,11,8.5,Lionel Messi,28003
1,Lionel Messi,InterMiami,2023,14,11,5,8.0,Lionel Messi,28003
2,Lionel Messi,PSG,2022/2023,41,21,20,8.1,Lionel Messi,28003
3,Lionel Messi,PSG,2021/2022,34,11,14,7.9,Lionel Messi,28003
4,Lionel Messi,Barcelona,2020/2021,47,38,12,8.4,Lionel Messi,28003
5,Lionel Messi,Barcelona,2019/2020,44,31,25,8.3,Lionel Messi,28003
6,Lionel Messi,Barcelona,2018/2019,50,51,19,8.5,Lionel Messi,28003
7,Lionel Messi,Barcelona,2017/2018,54,45,18,8.4,Lionel Messi,28003
8,Lionel Messi,Barcelona,2016/2017,52,54,16,8.4,Lionel Messi,28003
9,Cristiano Ronaldo,AL Nassr,2023/2024,51,50,13,8.1,Cristiano Ronaldo,8198
10,Cristiano Ronaldo,AL Nassr,2022/2023,19,14,2,7.7,Cristiano Ronaldo,8198
11,Cristiano Ronaldo,Man United,2021/2022,16,3,2,7.0,Cristiano Ronaldo,8198
12,Cristiano Ronaldo,Man United,2020/2021,38,24,3,7.5,Cristiano Ronaldo,8198
13,Cristiano Ronaldo,Juventus,2019/2020,1,0,0,6.7,Cristiano Ronaldo,8198
14,Cristiano Ronaldo,Juventus,2018/2019,44,36,5,7.9,Cristiano Ronaldo,8198
15,Cristiano Ronaldo,Juventus,2017/2018,43,28,10,7.9,Cristiano Ronaldo,8198
16,Cristiano Ronaldo,Real Madrid,2016/2017,46,42,11,7.9,Cristiano Ronaldo,8198
17,Cristiano Ronaldo,Real Madrid,2015/2016,48,51,15,8.6,Cristiano Ronaldo,8198
18,Neymar,AL Hilal,2023/2024,5,1,2,7.5,Neymar,68290
19,Neymar,PSG,2022/2023,29,18,16,8.0,Neymar,68290

## 6. Display Non-Matched Player Names
Show the player names from the first CSV that were not matched to any name in the second CSV.

In [20]:
# Find and display non-matched player names from the first CSV
matched_names_plain = set(matched_df_plain['Players'])
all_names = set(players_2024_df['Players'])
non_matched_names_plain = sorted(all_names - matched_names_plain)

print(f"Number of non-matched player names: {len(non_matched_names_plain)}")
for name in non_matched_names_plain:
    print(name)

Number of non-matched player names: 45
Alex Baena
Alex Balde
Alexis Sanchez
Alvaro Morata
Angel Correa
Angel Di Maria
Clement Lenglet
Eric Garcia
Fabian Ruiz
Fermin Lopez
Hector Bellerin
Heung Min Son
Ilkay Gundogan
Inaki Williams
Inigo Martinez
Jeremy Doku
Jesus Navas
Joao Cancelo
Joao Felix
Joaquin Correa
Jose Gimenez
Joseph Gomez
Jules Kounde
Julian Alvarez
Kamir Benzema
Kylian Mbappe
Lautaro Martinez
Leroy Sane
Lisandro Martinez
Lucas Vazquez
Luka Modric
Marc Guehi
Miguel Gutierrez
Mikel Oyarzabal
Nacho Fernandez
Nathan Ake
Nicolas Otamendi
Pau Cubarsi
Pedro Rodriguez
Rafael Leao
Raphael Guerreiro
Sadio Mane
Theo Hernandez
Thomas Muller
koke

## 7. Add a function to Normalize Player Names
Clean and normalize the player names in both DataFrames to improve matching accuracy.

In [27]:
# Function to normalize player names
def normalize_name(name):
    if pd.isnull(name):
        return ""
    # Lowercase, strip, remove special characters
    name = name.lower().strip()
    name = re.sub(r'[^a-z0-9 ]', '', name)
    name = re.sub(r'\s+', ' ', name)
    return name

# Apply normalization to both DataFrames
players_2024_df['Players_normalized'] = players_2024_df['Players'].apply(normalize_name)
transfermarkt_players_df['name_normalized'] = transfermarkt_players_df['name'].apply(normalize_name)

## 8. Match Player Names Across DataFrames After Normalization
Perform a merge operation to match player names from the 'Players' column in the first DataFrame with the 'name' column in the second DataFrame.

In [28]:
# Merge DataFrames on normalized player names
matched_df_normalized = pd.merge(
    players_2024_df,
    transfermarkt_players_df,
    left_on='Players_normalized',
    right_on='name_normalized',
    how='inner',
    suffixes=('_2024', '_tm')
)
print(f"Number of matched players: {len(matched_df_normalized)}")

Number of matched players: 1012

## 9. Display Matched Results After Normalization
Show the resulting DataFrame with matched player names and relevant columns from both datasets.

In [29]:
# Display the matched results
# Show selected columns for clarity
columns_to_show = [
    'Players', 'Teams', 'Seasons', 'Matches', 'Goals', 'Assists', 'Seasons Ratings',
    'name', 'player_id'
]
display(matched_df_normalized[columns_to_show].head(20))

,Players,Teams,Seasons,Matches,Goals,Assists,Seasons Ratings,name,player_id
0,Lionel Messi,InterMiami,2024,15,14,11,8.5,Lionel Messi,28003
1,Lionel Messi,InterMiami,2023,14,11,5,8.0,Lionel Messi,28003
2,Lionel Messi,PSG,2022/2023,41,21,20,8.1,Lionel Messi,28003
3,Lionel Messi,PSG,2021/2022,34,11,14,7.9,Lionel Messi,28003
4,Lionel Messi,Barcelona,2020/2021,47,38,12,8.4,Lionel Messi,28003
5,Lionel Messi,Barcelona,2019/2020,44,31,25,8.3,Lionel Messi,28003
6,Lionel Messi,Barcelona,2018/2019,50,51,19,8.5,Lionel Messi,28003
7,Lionel Messi,Barcelona,2017/2018,54,45,18,8.4,Lionel Messi,28003
8,Lionel Messi,Barcelona,2016/2017,52,54,16,8.4,Lionel Messi,28003
9,Cristiano Ronaldo,AL Nassr,2023/2024,51,50,13,8.1,Cristiano Ronaldo,8198
10,Cristiano Ronaldo,AL Nassr,2022/2023,19,14,2,7.7,Cristiano Ronaldo,8198
11,Cristiano Ronaldo,Man United,2021/2022,16,3,2,7.0,Cristiano Ronaldo,8198
12,Cristiano Ronaldo,Man United,2020/2021,38,24,3,7.5,Cristiano Ronaldo,8198
13,Cristiano Ronaldo,Juventus,2019/2020,1,0,0,6.7,Cristiano Ronaldo,8198
14,Cristiano Ronaldo,Juventus,2018/2019,44,36,5,7.9,Cristiano Ronaldo,8198
15,Cristiano Ronaldo,Juventus,2017/2018,43,28,10,7.9,Cristiano Ronaldo,8198
16,Cristiano Ronaldo,Real Madrid,2016/2017,46,42,11,7.9,Cristiano Ronaldo,8198
17,Cristiano Ronaldo,Real Madrid,2015/2016,48,51,15,8.6,Cristiano Ronaldo,8198
18,Neymar,AL Hilal,2023/2024,5,1,2,7.5,Neymar,68290
19,Neymar,PSG,2022/2023,29,18,16,8.0,Neymar,68290

## 10. Display Non-Matched Player Names after Normalization
Show the player names from the first CSV that were not matched to any name in the second CSV.

In [30]:
# Find and display non-matched player names from the first CSV
matched_names_normalized = set(matched_df_normalized['Players'])
all_names = set(players_2024_df['Players'])
non_matched_names_normalized = sorted(all_names - matched_names_normalized)

print(f"Number of non-matched player names: {len(non_matched_names_normalized)}")
for name in non_matched_names_normalized:
    print(name)

Number of non-matched player names: 43
Alex Baena
Alex Balde
Alexis Sanchez
Alvaro Morata
Angel Correa
Angel Di Maria
Clement Lenglet
Eric Garcia
Fabian Ruiz
Fermin Lopez
Hector Bellerin
Heung Min Son
Ilkay Gundogan
Inaki Williams
Inigo Martinez
Jeremy Doku
Jesus Navas
Joao Cancelo
Joao Felix
Joaquin Correa
Jose Gimenez
Joseph Gomez
Jules Kounde
Julian Alvarez
Kamir Benzema
Kylian Mbappe
Lautaro Martinez
Leroy Sane
Lisandro Martinez
Lucas Vazquez
Luka Modric
Marc Guehi
Miguel Gutierrez
Nacho Fernandez
Nathan Ake
Nicolas Otamendi
Pau Cubarsi
Pedro Rodriguez
Rafael Leao
Raphael Guerreiro
Sadio Mane
Theo Hernandez
Thomas Muller

## 11. Improve the Normalization Function Treating Special Characters

Convert special characters (such as vowels with accents) to teh corresponding character as part of the 
normalization, and run matching again

In [32]:
# Function to normalize player names
def normalize_name(name):
    if pd.isnull(name):
        return ""
    # Lowercase, strip, remove special characters
    name = name.lower().strip()
    # Remove accents: decompose unicode and keep only ASCII characters
    name = unicodedata.normalize('NFD', name)
    name = ''.join(c for c in name if unicodedata.category(c) != 'Mn')
    # Remove special characters
    name = re.sub(r'[^a-z0-9 ]', '', name)
    name = re.sub(r'\s+', ' ', name)
    return name

# Apply normalization to both DataFrames
players_2024_df['Players_normalized'] = players_2024_df['Players'].apply(normalize_name)
transfermarkt_players_df['name_normalized'] = transfermarkt_players_df['name'].apply(normalize_name)

# Merge DataFrames on normalized player names
matched_df_normalized = pd.merge(
    players_2024_df,
    transfermarkt_players_df,
    left_on='Players_normalized',
    right_on='name_normalized',
    how='inner',
    suffixes=('_2024', '_tm')
)
print(f"Number of matched players: {len(matched_df_normalized)}")

# Find and display non-matched player names from the first CSV
matched_names_normalized = set(matched_df_normalized['Players'])
all_names = set(players_2024_df['Players'])
non_matched_names_normalized = sorted(all_names - matched_names_normalized)

print(f"Number of non-matched player names: {len(non_matched_names_normalized)}")
for name in non_matched_names_normalized:
    print(name)

Number of matched players: 1281
Number of non-matched player names: 6
Alex Balde
Heung Min Son
Jose Gimenez
Joseph Gomez
Kamir Benzema
Pedro Rodriguez

## 12. Display Names Matched Only After Normalization
Show the player names that were matched in the normalization step but not in the plain step.

In [33]:
# Find names matched only after normalization
matched_names_plain = set(matched_df_plain['Players'])
matched_names_normalized = set(matched_df_normalized['Players'])

matched_only_after_normalization = sorted(matched_names_normalized - matched_names_plain)

print(f"Number of player names matched only after normalization: {len(matched_only_after_normalization)}")
for name in matched_only_after_normalization:
    print(name)

Number of player names matched only after normalization: 39
Alex Baena
Alexis Sanchez
Alvaro Morata
Angel Correa
Angel Di Maria
Clement Lenglet
Eric Garcia
Fabian Ruiz
Fermin Lopez
Hector Bellerin
Ilkay Gundogan
Inaki Williams
Inigo Martinez
Jeremy Doku
Jesus Navas
Joao Cancelo
Joao Felix
Joaquin Correa
Jules Kounde
Julian Alvarez
Kylian Mbappe
Lautaro Martinez
Leroy Sane
Lisandro Martinez
Lucas Vazquez
Luka Modric
Marc Guehi
Miguel Gutierrez
Mikel Oyarzabal
Nacho Fernandez
Nathan Ake
Nicolas Otamendi
Pau Cubarsi
Rafael Leao
Raphael Guerreiro
Sadio Mane
Theo Hernandez
Thomas Muller
koke

## 12. Write Matched Players Table After Normalization

In [26]:
# Save the matched_df_normalized DataFrame to a CSV file
matched_df_normalized.to_csv('matched_players_full.csv', index=False)
print("Matched players with all data have been saved to 'matched_players_full.csv'")

Matched players with all data have been saved to 'matched_players_full.csv'